### ISSUE TITLE
ROC Curve

### ISSUE THREAD

**Issue by prakhar123pradhan** [yhlleo/DeepCrack#2]
Hello Sir!
Can you please provide code to generate the ROC curve, Figure 8 in the paper?

**Comment by yhlleo** [comment]
I'm sorry that I lost the codes for the Figure 8. But, you find out the similar codes in [Sklearn](https://scikit-learn.org/stable/auto_examples/ensemble/plot_feature_transformation.html#sphx-glr-auto-examples-ensemble-plot-feature-transformation-py).
