### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Dong0604** [yhlleo/DeepCrack#4]
Hello, @yhlleo 
I am facing this problem is it possible to get any clarification on what I should do?

RuntimeError: Error(s) in loading state_dict for DeepCrackNet:
	Unexpected key(s) in state_dict: "conv1.1.weight", "conv1.1.bias", "conv1.4.weight", "conv1.4.bias", "conv2.1.weight", "conv2.1.bias", "conv2.4.weight", "conv2.4.bias", "conv3.1.weight", "conv3.1.bias", "conv3.4.weight", "conv3.4.bias", "conv3.7.weight", "conv3.7.bias", "conv4.1.weight", "conv4.1.bias", "conv4.4.weight", "conv4.4.bias", "conv4.7.weight", "conv4.7.bias", "conv5.1.weight", "conv5.1.bias", "conv5.4.weight", "conv5.4.bias", "conv5.7.weight", "conv5.7.bias". 
	size mismatch for side_conv1.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 64, 1, 1]).
	size mismatch for side_conv2.weight: copying a param with shape torch.Size([1, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 128, 1, 1]).
	size mismatch for side_conv3.weight: copying a param with shape torch.Size([1, 256, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 256, 1, 1]).
	size mismatch for side_conv4.weight: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 512, 1, 1]).
	size mismatch for side_conv5.weight: copying a param with shape torch.Size([1, 512, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 512, 1, 1]).
	size mismatch for fuse_conv.weight: copying a param with shape torch.Size([1, 5, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 10, 1, 1]).

Process finished with exit code 1

**Comment by yhlleo** [comment]
@Dong0604  It seems the loaded model is with different architecture, which leads to unknown keys (this can be solved by setting `strict=False` in `load_state_dict`) and the shape is different for some layers (please check the model again).
